runtime: python38
entrypoint: gunicorn -c gunicorn_config.py main:app
instance_class: F4

env_variables:
  MODEL_PATH: 'models/best_rdd_final.pt'

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto