runtime: python
runtime_config:
  operating_system: "ubuntu18"
  runtime_version: "3.8"

timeout: 3600s

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  MODEL_PATH: 'models/best_rdd_final2.pt'

env: flex
resources:
  cpu: 4
  memory_gb: 8

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
